"use client"

import { useState, useEffect, useRef, useCallback } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { ScanLine, Zap, Hash, CameraOff, X } from "lucide-react"

interface QrScannerStepProps {
  onChargerFound: (chargerId: string) => void
}

/** Extract charger ID from a raw QR value.
 *  QR codes generated by the server encode a URL like:
 *    http://<ip>:3001/?chargerId=A20223115843
 *  If the value looks like a URL with that param, use it.
 *  Otherwise treat the raw string as the ID directly.
 */
function extractChargerId(raw: string): string {
  try {
    const url = new URL(raw)
    const id = url.searchParams.get("chargerId")
    if (id) return id
  } catch {
    // Not a URL — fall through
  }
  return raw.trim()
}

export function QrScannerStep({ onChargerFound }: QrScannerStepProps) {
  const [manualId, setManualId] = useState("")
  const [isScanning, setIsScanning] = useState(false)
  const [error, setError] = useState("")
  const [cameraError, setCameraError] = useState("")

  // Refs for the scanner instance and DOM element
  const scannerRef = useRef<InstanceType<typeof import("html5-qrcode")["Html5Qrcode"]> | null>(null)
  const viewfinderDivId = "qr-viewfinder"

  /** Stop and clean up the scanner */
  const stopScanner = useCallback(async () => {
    if (scannerRef.current) {
      try {
        const state = scannerRef.current.getState()
        // State 2 = SCANNING
        if (state === 2) {
          await scannerRef.current.stop()
        }
      } catch {
        // Ignore errors on stop
      }
      scannerRef.current = null
    }
    setIsScanning(false)
  }, [])

  /** Start the camera scanner */
  async function handleScan() {
    setError("")
    setCameraError("")

    // Dynamically import to avoid SSR issues
    const { Html5Qrcode } = await import("html5-qrcode")

    const scanner = new Html5Qrcode(viewfinderDivId)
    scannerRef.current = scanner
    setIsScanning(true)

    try {
      await scanner.start(
        { facingMode: "environment" }, // rear camera
        {
          fps: 10,
          qrbox: { width: 220, height: 220 },
          aspectRatio: 1.0,
        },
        (decodedText) => {
          // Success callback — extract charger ID and stop
          const chargerId = extractChargerId(decodedText)
          stopScanner().then(() => {
            onChargerFound(chargerId)
          })
        },
        () => {
          // Per-frame no-match — ignore silently
        }
      )
    } catch (err: unknown) {
      await stopScanner()
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.toLowerCase().includes("permission")) {
        setCameraError("Camera permission denied. Please allow camera access and try again.")
      } else if (msg.toLowerCase().includes("notfound") || msg.toLowerCase().includes("no cameras")) {
        setCameraError("No camera found on this device. Use manual entry below.")
      } else {
        setCameraError("Could not start camera: " + msg)
      }
    }
  }

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      stopScanner()
    }
  }, [stopScanner])

  function handleManualEntry() {
    setError("")
    const id = manualId.trim().toUpperCase()
    if (!id) {
      setError("Please enter a charger ID")
      return
    }
    onChargerFound(id)
  }

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardHeader className="text-center">
          <div className="mx-auto mb-2 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10">
            <Zap className="h-8 w-8 text-primary" />
          </div>
          <CardTitle className="text-xl">Scan Charger QR Code</CardTitle>
          <CardDescription>
            Point your camera at the QR code on the EV charger, or enter the charger ID manually
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center gap-4">

          {/* Camera viewfinder — always rendered so html5-qrcode can mount into it */}
          <div
            id={viewfinderDivId}
            className={
              isScanning
                ? "w-full max-w-xs overflow-hidden rounded-2xl border border-primary/30"
                : "hidden"
            }
          />

          {/* Scanning controls */}
          {isScanning ? (
            <Button
              variant="outline"
              onClick={stopScanner}
              className="flex items-center gap-2"
            >
              <X className="h-4 w-4" />
              Stop Scanning
            </Button>
          ) : (
            <button
              onClick={handleScan}
              className="group relative mx-auto flex h-52 w-52 cursor-pointer items-center justify-center overflow-hidden rounded-2xl border-2 border-dashed border-primary/25 bg-primary/5 transition-all hover:border-primary/50 hover:bg-primary/10"
              aria-label="Tap to scan QR code"
            >
              <div className="flex flex-col items-center gap-3">
                <ScanLine className="h-12 w-12 text-primary/60 transition-colors group-hover:text-primary" />
                <span className="text-sm font-medium text-muted-foreground">
                  Tap to scan
                </span>
              </div>
            </button>
          )}

          {/* Camera error message */}
          {cameraError && (
            <div className="flex items-center gap-2 rounded-lg bg-destructive/10 px-4 py-3 text-sm text-destructive">
              <CameraOff className="h-4 w-4 shrink-0" />
              {cameraError}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="flex items-center gap-4">
        <div className="h-px flex-1 bg-border" />
        <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
          or enter manually
        </span>
        <div className="h-px flex-1 bg-border" />
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="flex flex-col gap-3">
            <label
              htmlFor="charger-id"
              className="text-sm font-medium text-foreground"
            >
              Charger ID
            </label>
            <div className="flex gap-2">
              <div className="relative flex-1">
                <Hash className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  id="charger-id"
                  placeholder="e.g. A20223115843"
                  value={manualId}
                  onChange={(e) => {
                    setManualId(e.target.value)
                    setError("")
                  }}
                  onKeyDown={(e) => e.key === "Enter" && handleManualEntry()}
                  className="pl-9"
                />
              </div>
              <Button onClick={handleManualEntry}>Connect</Button>
            </div>
            {error && (
              <p className="text-sm text-destructive" role="alert">
                {error}
              </p>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="rounded-lg border border-primary/15 bg-primary/5 p-4">
        <p className="text-xs text-muted-foreground leading-relaxed">
          <span className="font-semibold text-foreground">Tip:</span>{" "}
          The charger ID is printed on the charger and encoded in the QR code. You can also enter it manually using the field above.
        </p>
      </div>
    </div>
  )
}
